---
apiVersion: v1
kind: Secret
metadata:
  name: mysecretname
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZG5qemFmc2V1Cg==
  CLOUDINARY_KEY: NjIxNTQzMTIyNzUyNjE0Cg==
  CLOUDINARY_SECRET: bVBBY3dkTXE2VUxQX0kyTjNpTHdnbmp2WTRZCg==
  MAPBOX_TOKEN: c2suZXlKMUlqb2liV0Z5ZVdGdGJXRnBjbUZxSWl3aVlTSTZJbU50TXpobmQyTXdjakJ6TWpreWNYRjRjV1l5ZW5WdFptSWlmUS5lbFZjdk5zQl9Hckh5RVdHbEs5dUFBCg==
  DB_URL: by41Y2RlNC5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9bWFyeWFtLW1vbmdvCg==
  SECRET: bWFyeWFtc2VjcmV0Cg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: maryammairaj/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecretname
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecretname
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecretname
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mysecretname
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mysecretname
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecretname
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
